crawler:
  target_num: 200
  user_agent: 'Mozilla/5.0'
  mail: 'euthanasia045@gmail.com'
  wait_sec: 0.01
  ext: 'png'

  for_expart:
    dropout_img_squares: False
    output_imglog: False
    parser: 'lxml'
    save_bin: False

ml:
  model: 'MobileNet' # NoneでoriginalNN
  test_data_rate: 0.3
  grayscale: True